//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Yolia.App.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomicilioSet
    {
        public int DomicilioId { get; set; }
        public string Calle { get; set; }
        public string NumInterior { get; set; }
        public string NumExterior { get; set; }
        public string Colonia { get; set; }
        public string Estado { get; set; }
        public string CodPostal { get; set; }
        public int ClienteClienteId { get; set; }
    
        public virtual ClienteSet ClienteSet { get; set; }
    }
}
