//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Yolia.App.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioSet
    {
        public int FolioServicio { get; set; }
        public System.DateTime FechaIniServicio { get; set; }
        public System.DateTime FechaFinServicio { get; set; }
        public string TipoServicio { get; set; }
        public int ClienteClienteId { get; set; }
        public int Pago_FolioPago { get; set; }
    
        public virtual ClienteSet ClienteSet { get; set; }
        public virtual PagoSet PagoSet { get; set; }
    }
}
