// <auto-generated />
namespace com.Yolia.App.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pagoservicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pagoservicio));
        
        string IMigrationMetadata.Id
        {
            get { return "201705011701064_pago-servicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
